version: 2
registries:
  git-bitbucket-org:
    type: git
    url: https://bitbucket.org
    username: x-access-token.
    password: "${{secrets.GIT_BITBUCKET_ORG_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  registries:
  - git-bitbucket-org
